### ISSUE TITLE
插件升级报错

### ISSUE THREAD

**Issue by hwy1782** [obgnail/typora_plugin#370]
使用本地代理，插件升级报错，截图如下：

![image](https://github.com/obgnail/typora_plugin/assets/2442046/a3962219-da73-4b67-89e1-0b403bdeff72)

![image](https://github.com/obgnail/typora_plugin/assets/2442046/575de72c-7110-4e6c-87a8-a325986a47cb)

升级命令如下：
```
updater.exe --action=update --proxy=http://http=http://127.0.0.1:7890;https=http://127.0.0.1:7890
```

错误描述如下：

```
升级中，请稍等

[1/9] new updater
[2/9] check whether need update

panic: Get "https://api.github.com/repos/obgnail/typora_plugin/releases/latest": proxyconnect tcp: dial tcp: lookup http=http: no such host
D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:209: 
D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:178: 
D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:566: 
D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:617: 

goroutine 1 [running]:
main.main()
	D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:617 +0x26d
```

**Comment by obgnail** [comment]
你好，感谢反馈。

proxy填错了，不是填入
http=http://127.0.0.1:7890;https=http://127.0.0.1:7890

填入127.0.0.1:7890即可

**Comment by hwy1782** [comment]
感谢，直接在命令行中执行：updater.exe --action=update --proxy=http://127.0.0.1:7890 升级成功。
ps 上述升级命令是插件中自动生成的，这部分自动生成可能存在一些问题。
