### ISSUE TITLE
`Package.File.filePath` 无法正确获取文件路径

### ISSUE THREAD

**Issue by Shadowalker1995** [obgnail/typora_plugin#5]
Version: Typora for Linux (x64) 1.6.6

遇到的错误信息如下：

```
de:internal/errors:490 Uncaught (in promise) TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at __node_internal_ (node:internal/fs/utils:675:11)
    at __node_internal_ (node:internal/fs/utils:687:3)
    at Object.openSync (node:fs:592:10)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:468:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at read (/usr/share/typora/resources/plugin/md_padding/index.js:24:41)
    at /usr/share/typora/resources/plugin/md_padding/index.js:47:33
_
```

文件 `plugin/md_padding/index.js:47:33` 及相关行的内容如下：

```
    const getFilePath = () => Package.File.filePath;
...
            save().then(() => {
                const filepath = getFilePath();
                const content = read(filepath);
                const formattedContent = format(content);
                write(filepath, formattedContent);
            })
```

猜测应该是获取文件路径的语句有问题 `Package.File.filePath`.
请问这个应该改成什么呢？

**Comment by Shadowalker1995** [comment]
这个问题我解决了：

将 `Package.File.filePath` 改为 `Package.File.bundle.filePath` 即可

现在使用快捷键Ctrl+Shift+K，console不会报错了，但没有任何效果，中英文之间没有空格，请问这个问题要怎么解决呢？

**Comment by obgnail** [comment]
你好，感谢反馈。

脚本尚未在 Linux 平台测试（主要是我不知道 Typora 有 Linux 版本）

我明天搭个环境测一下，有进展的话会在这里回复。

**Comment by obgnail** [comment]
@Shadowalker1995 不好意思，久等了。

这个问题和这个 [issue](https://github.com/obgnail/typora_plugin/issues/19) 是一样的。可以更新脚本解决。

原因：脚本核心逻辑没有问题。高版本 Typora 的 reloadContent 函数发生了变化，导致文件内容更新了，但是没有更新页面。
