### ISSUE TITLE
按钮和更新功能异常

### ISSUE THREAD

**Issue by I-Loving321** [obgnail/typora_plugin#671]
留心反馈，只读功能和图片预览功能的按钮触发区域不正常，以及最近的更新功能受限

**Comment by obgnail** [comment]
@I-Loving321 

你好，感谢反馈。麻烦能详细说明一下吗？

**Comment by I-Loving321** [comment]
![123](https://github.com/user-attachments/assets/86170206-d551-4a71-bdaf-8a44390502da)

**Comment by I-Loving321** [comment]
![Uploading 123.png…]()

**Comment by I-Loving321** [comment]
升级中，请稍等

[1/9] new updater
[2/9] check whether need update

panic: Get "https://api.github.com/repos/obgnail/typora_plugin/releases/latest": proxyconnect tcp: dial tcp 127.0.0.1:15732: connectex: No connection could be made because the target machine actively refused it.
D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:209: 
D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:178: 
D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:566: 
D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:617: 

goroutine 1 [running]:
main.main()
	D:/golang/src/github.com/obgnail/typora_plugin/plugin/updater/updater.go:617 +0x26d
![Uploading 123.png…]()

**Comment by I-Loving321** [comment]
![123](https://github.com/user-attachments/assets/34ef528a-e377-45a3-b926-6d47dbae53bb)

**Comment by obgnail** [comment]
@I-Loving321 

看截图，报错原因是你给的代理 url 有问题导致的，没有 `127.0.0.1:15732` 这个代理。

如果你有使用 clash 之类的软件，请检查代理的端口；如果没有，并且你所在地区能直连 github，可以将代理的 url 置为空

**Comment by I-Loving321** [comment]
谢谢作者，置空后成功更新

**Comment by obgnail** [comment]
@I-Loving321 

【只读功能和图片预览功能的按钮触发区域不正常】麻烦能详细说明吗？

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言。
