### ISSUE TITLE
新插件drawio 报错

### ISSUE THREAD

**Issue by inkwelllee** [obgnail/typora_plugin#879]
![image](https://github.com/user-attachments/assets/aac94e01-8863-441e-bdf6-bbeef120c934)
Error: 读取本地文件失败: E:\Sync Folder\my-notes\notes\assets\example.drawio

Error: ENOENT: no such file or directory, open 'E:\Sync Folder\my-notes\notes\assets\example.drawio'
    at drawIOPlugin._getXML (D:\SoftMgr\Typora\resources\plugin\custom\plugins\drawIO\index.js:58:19)
    at async Object.create [as createFunc] (D:\SoftMgr\Typora\resources\plugin\custom\plugins\drawIO\index.js:36:9)
    at async Object.render [as renderFunc] (D:\SoftMgr\Typora\resources\plugin\global\core\utils\mixin\thirdPartyDiagramParser.js:66:28)
    at async diagramParser.renderCustomDiagram (D:\SoftMgr\Typora\resources\plugin\global\core\utils\mixin\diagramParser.js:181:13)
    at async diagramParser.renderDiagram (D:\SoftMgr\Typora\resources\plugin\global\core\utils\mixin\diagramParser.js:206:17)

diagram parser settings:
    diagram version: 24.8.9
    mapping language: javascript
    interactive mode: true
    destroy when update: false
    render element: <div class="plugin-drawio-content"></div>

**Comment by obgnail** [comment]
@inkwelllee 

这个插件刚起步，目前的功能仅有显示功能，只能显示现有的 .drawio 文件。

报错里也说明了，需要本地或者网络的 drawio 文件。你保存如下文件 `E:\Sync Folder\my-notes\notes\assets\example.drawio` 就可以了。

**Comment by inkwelllee** [comment]
哦，好的

**Comment by obgnail** [comment]
补充说明：

目前使用此插件的方法为：首先在 [draw.io](https://app.diagrams.net/) 里将图片保存为本地或网络的 .drawio 文件，然后在 source 配置项指向此文件。
